Month 9/step 1
Yuriy1989/react-burger pull request #6
Opened 2022-10-26 10:02 UTC by Yura1989

Month 9/step 1

2022-10-26 13:49 UTC, randomroot requested changes
**Доброго времени суток!**

Вы проделали **хорошую** работу по добавлению новых экранов, вёрстка и работа с API была выполнена **практически полностью** корректно, осуществляется проверка на **защищенность** пути, код **лаконичный**, так держать 👍 

Однако, для успешной сдачи работы вам необходимо внести **изменения**, согласно комментариям к ревью, обратив особое внимание на следующие моменты:

**Нужно исправить:**

- В случае ответа сервера кодом ошибки 401 или 403 следует обновлять `accessToken` пользователя через `refreshToken`, либо перенаправлять его на экран логина при неудаче обновления;
- Экран конструктора, согласно заданию, является незащищенным роутом, поэтому следует разрешить неавторизованному пользователю работать с ним, и только при попытке заказа отправлять пользователя на экран логина. Такой подход вы можете заметить практически во всех онлайн магазинах, где добавить товар в корзину можно еще до авторизации;
- На экране профиля пользователя при клике на «История заказов» должен происходить переход на экран `/profile/orders`, где ссылка «История заказов» становится активной, а экран `/profile/orders` пока отображается пустым.
- Кнопки сохранения и отмена при редактировании данных пользователя следует отображать, только если были внесены новый данные пользователя и скрывать при нажатии отмены или выполнении запроса на сервер;

**Можно улучшить:**
- Обратите внимание, что наличие токена ещё не значит, что он будет принят сервером, поэтому правильно при прямом переходе на защищенную страницу, даже при наличии токена, отправлять запрос на сервер (например запрос получения данных пользователя) и только если запрос будет выполнен и токен принят, можно отображать защищенную страницу. На время выполнения этого запроса проверяющего актуальность токена нужно отображать прелоадер, а при завершении запроса в случае успеха отображать защищенный компонент, а в случае ошибки - очищать токен и перенаправлять на страницу входа.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**.

---

**Успешного вам рефакторинга и отличного настроения!** 🐈

2022-10-26 13:49 UTC, randomroot commented on src/pages/register.js
> +          <EmailInput onChange={onChange} value={data.email} name={'email'} />
🔴 **Нужно исправить:**

По макету у полей ввода на страницах входа и регистрации нет кнопки активации редактирования, эта кнопка есть только у полей ввода на странице профиля. Используйте не компонент `EmailInput`, а просто компонент `Input` с пропсом `type="email"`

2022-10-26 13:49 UTC, randomroot commented on src/components/app/App.js
> +                  <AppHeader />
🔴 **Нужно исправить:**

Компонент `AppHeader` показывается на всех экранах, поэтому его не следует дублировать в каждом роуте и необходимо вынести за пределы роутинга

2022-10-26 13:49 UTC, randomroot commented on src/components/app/App.js
> +          <DndProvider backend={HTML5Backend}>
🟡 **Можно улучшить:**

`DndProvider` используется только на экране конструктора бургера, поэтому целесообразно перенести его в соответствующий роут, чтобы не нагружать другие компоненты

2022-10-26 13:49 UTC, randomroot commented on src/components/app/App.js
> +              <ProtectedRoute path="/" exact={true}>
🔴 **Нужно исправить:**

Экран конструктора, согласно заданию, является незащищенным роутом, поэтому следует разрешить неавторизованному пользователю работать с ним

2022-10-26 13:49 UTC, randomroot commented on src/components/app/App.js
> +  // if (accessToken) {
🟡 **Можно улучшить:**

Неиспользуемый код следует удалять из файла

2022-10-26 16:40 UTC, Yuriy1989 commented on src/utils/cookie.js
> +    if (propValue !== true) {
Выполнено

2022-10-26 16:48 UTC, Yuriy1989 commented on src/utils/Api.js
> +      .then(res => res.ok ? res.json() : Promise.reject(res.status))
Выполнено

2022-10-26 16:49 UTC, Yuriy1989 commented on src/utils/Api.js
> +    console.log('refreshToken API', refreshToken);
Выполнено

2022-10-26 17:00 UTC, Yuriy1989 commented on src/pages/register.js
> +          <EmailInput onChange={onChange} value={data.email} name={'email'} />
Выполнено

2022-10-26 17:05 UTC, Yuriy1989 commented on src/components/app/App.js
> +                  <AppHeader />
Выполнено

2022-10-26 18:51 UTC, Yuriy1989 commented on src/components/app/App.js
> +          <DndProvider backend={HTML5Backend}>
Выполнено

2022-10-26 18:55 UTC, Yuriy1989 commented on src/components/app/App.js
> +              <ProtectedRoute path="/" exact={true}>
Выполнено

2022-10-26 18:55 UTC, Yuriy1989 commented on src/components/app/App.js
> +  // if (accessToken) {
Выполнено

2022-10-26 18:58 UTC, Yuriy1989 commented on src/components/appHeader/AppHeader.js
> +                <BurgerIcon type={ history.location.pathname == '/' ? 'primary' : 'secondary' }/>
Выполнено

2022-10-26 19:03 UTC, Yuriy1989 commented on src/components/burgerConstructor/BurgerConstructor.js
> +      if (selectedIngredients.bun.find(item => item.type === 'bun')) {
Выполнено

2022-10-26 19:07 UTC, Yuriy1989 commented on src/components/ingredientDetails/IngredientDetails.js
> +  if (!accessToken) {
Выполнено

2022-10-26 19:11 UTC, Yuriy1989 commented on src/pages/forgot-password.js
> +  const [email, setEmail] = useState('test@yandex.ru');
Выполнено

2022-10-27 10:48 UTC, Yura1989 commented on src/pages/login.js
> +              setCookie('accessToken', accessToken, { 'max-age': 120 });
Выполнено

2022-11-02 06:42 UTC, randomroot requested changes
**Здравствуйте!**

Большая часть изменений была успешно применена, осталось совсем немного до успешного завершения, работа будет принята после исправления следующих моментов:

- При отправке формы данных пользователя не учитывается значения поля "Пароль" (https://disk.yandex.ru/i/dsYxDWf3M-hHNw)
- После нажатия кнопки "Выход" экраны, недоступные авторизованным пользователям остаются недоступными и для анонимного пользователя (например, попробуйте перейти на страницу регистрации после выхода). Это связано с тем, что, когда вы записываете кукис со значением `null` в функции `deleteCookie` он на самом деле превращается в строку с текстом "null", поэтому обратно вернется именно строка и проверка на пустоту `accessToken` не отработает (https://disk.yandex.ru/i/pBE5b6ylFGhkKw). Замените `null` на пустую строку - тогда всё будет хорошо :)

Также добавлены еще немного предложений по улучшению вашего кода.

**Хорошего дня!** 🐈

2022-11-02 06:42 UTC, randomroot commented on src/pages/login.js
> +  if (isAuth) {
🟡 **Можно улучшить:**

Здесь и для других страниц, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а создайте либо отдельный компонент `OnlyUnAuthRoute`, по аналогии c `ProtectedRoute`, который будет защищать эти страницы от авторизированных пользователей или доработайте компонент `ProtectedRoute`, передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

`const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {`

если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный path доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2022-11-02 06:42 UTC, randomroot commented on src/pages/profile.js
> +  //Обновление данных о пользователе, с сохранением их в Store
🟡 **Можно улучшить:**

Имеет смысл отключать кнопки после успешной отправки, т.к. форма получается после этого неизменненной, и на время выполнения запроса, чтобы пользователь наглядно видел, что идёт выполнение :)

2022-11-02 06:42 UTC, randomroot commented on src/pages/profile.js
> +          <p >В этом разделе вы можете изменить свои персональные данные</p>
🟡 **Можно улучшить:**

Обратите внимание, что текст в разных подразделах личного кабинета отличается

2022-11-02 06:42 UTC, randomroot commented on src/services/actions/actionsAuthorization.js
> +  const timeCookie = 60;
🟡 **Можно улучшить:**

1) Время жизни токена имеет смысл увеличить, так как оно составляет на самом деле 20 минут, это значение вы можете проверить, если скопируете ваш токен в форму на сайте https://jwt.io/ (https://disk.yandex.ru/i/cc5NY5o9W_nZEw - разница между `exp` и `iat`).

Сейчас ваш токен живёт всего одну минуту

2) Константу лучше вынести за пределы функции, чтобы переиспользовать её далее по коду

2022-11-02 06:42 UTC, randomroot commented on src/services/actions/actionsAuthorization.js
> +        if (res.success === true) {
🟡 **Можно улучшить:**

Не следует сравнивать логические значения с `true/false` - это считается плохой практикой

2022-11-02 06:42 UTC, randomroot commented on src/services/actions/actionsAuthorization.js
> +            let accessToken = res.accessToken.split('Bearer ')[1];
🟡 **Можно улучшить:**

Данную переменную можно сделать константой, т.к. она далее не изменяется по коду

2022-11-02 06:42 UTC, randomroot commented on src/utils/cookie.js
> +export function setCookie(name, value, options = {}) {
🟡 **Можно улучшить:**

В тренажере приводится не совсем корректный пример этой функции, там не задается path и возможна ситуация, когда на разных страницах в cookies будут разные токены, поэтому в **options.path** нужно задавать корень сайта path: '/'

2022-11-02 12:40 UTC, Yura1989 commented on src/pages/profile.js
> +  //Обновление данных о пользователе, с сохранением их в Store
Выполнено

2022-11-02 16:44 UTC, Yuriy1989 commented on src/pages/profile.js
> +          <p >В этом разделе вы можете изменить свои персональные данные</p>
Выполнено

2022-11-02 16:51 UTC, Yuriy1989 commented on src/services/actions/actionsAuthorization.js
> +  const timeCookie = 60;
Выполнено

2022-11-02 16:52 UTC, Yuriy1989 commented on src/services/actions/actionsAuthorization.js
> +        if (res.success === true) {
Выполнено

2022-11-02 16:54 UTC, Yuriy1989 commented on src/services/actions/actionsAuthorization.js
> +            let accessToken = res.accessToken.split('Bearer ')[1];
Выполнено

2022-11-02 16:55 UTC, Yuriy1989 commented on src/utils/cookie.js
> +export function setCookie(name, value, options = {}) {
Выполнено

2022-11-02 18:52 UTC, Yuriy1989 commented on src/pages/login.js
> +  if (isAuth) {
Выполнено

2022-11-02 19:22 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-11-02 19:22 UTC, randomroot commented on src/pages/profile.js
> +                <Button disabled={data.buttonActive ? false : true} onClick={handleClickSave} type="primary" size="medium">
🟡 **Можно улучшить:**

Значение пропса можно вычислить проще: `disabled={!data.buttonActive}`

2022-11-03 03:17 UTC, Yura1989 commented on src/pages/profile.js
> +                <Button disabled={data.buttonActive ? false : true} onClick={handleClickSave} type="primary" size="medium">
Выполнено

2022-11-03 03:18 UTC, Yura1989 commented
Все замечания исправлены

2022-11-03 03:19 UTC, Yura1989 commented
Все замечания исправлены

2022-11-03 03:23 UTC, Yura1989 commented
Все замечания исправлены

2022-11-03 03:53 UTC, merged